apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: dockerhub-secret
  namespace: fakkudownloader-v2
spec:
  itemPath: "vaults/Home Server/items/dockerhub-secret"
type: kubernetes.io/dockerconfigjson