apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fakkudownloader-v2-secrets
  namespace: fakkudownloader-v2
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  itemPath: "vaults/Home Server/items/fakkudownloader-v2-secrets"
